# Pandas

In [2]:
import pandas as pd

### Creating Data :

There are two objects in pandas : the DataFrame and the Series

### DataFrame :

A DataFrame is a table. It contains an array of individual enteries, each of which has a certain value. Each entry corresponds to a row (or recoed) and a column.

In [2]:
pd.DataFrame({"Yes" : [50, 21], "No" : [131, 2]})

   Yes   No
0   50  131
1   21    2

In [3]:
## DataFrame whoes value are string:
pd.DataFrame({"Bob" :["I liked it.", "It was awful."], "Sue" : ["Pretty Good.", "Bland"]})

             Bob           Sue
0    I liked it.  Pretty Good.
1  It was awful.         Bland

In [4]:
## The list of row labels used in a DataFrame is known as an Index. We can assign values to it by using an index parameter in our constructor:

pd.DataFrame({"Bob" : ["I liked it.", "It was awful"],
              "Sue" : ["Pretty Good", "Bland"]}, 
             index = ["Product A", "Product B"])

                    Bob          Sue
Product A   I liked it.  Pretty Good
Product B  It was awful        Bland

### Series :

A Series by contrast, is a sequence of data values. if a DataFrame is a table, a Series is a list. And infact we can create one with nothing more than a list :

In [5]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
## A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series the same way as before, using an index parameter. However, a Series does not have a column name, it only has one overall name:

pd.Series([30, 35, 40], index = ["2015 Sales", "2016 Sales", "2017 Sales"], name = "Product A")

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [3]:
## Reading Data Files : pd.read_csv()

wine_reviews = pd.read_csv(".././datasets/winemag-data-130k-v2.csv")

In [ ]:
wine_reviews = pd.read_csv(r"D:\DA_DS_Journey\04_EDA\datasets\winemag-data-130k-v2.csv")

In [ ]:
## We can use shape attribute to check how large the resulting DataFrame is :

wine_reviews.shape

(129971, 14)

In [ ]:
## We can examine the contents of the resultant DataFrame using the head() command, which grabs the first five rows

wine_reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
## The pd.read_csv() function is well-endowed, with over 30 optional parameters you can specify. For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an index_col.

wine_reviews = pd.read_csv("../../datasets/winemag-data-130k-v2.csv", index_col = 0)
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
## Save a DataFrame to csv : to_csv

animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(animals)

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [ ]:
animals.to_csv("cows_and_goats.csv")