In [1]:
import pandas as pd

In [2]:
## Reading Data Files : pd.read_csv()

wine_reviews = pd.read_csv(".././datasets/winemag-data-130k-v2.csv")

In [3]:
wine_reviews = pd.read_csv(r"D:\DA_DS_Journey\04_EDA\datasets\winemag-data-130k-v2.csv")

In [4]:
## We can use shape attribute to check how large the resulting DataFrame is :

wine_reviews.shape

(129971, 14)

### Summary functions 

Pandas provides many simple "summary functions" (not an official name) which restructure the data in some useful way. For example, consider the describe() method:

In [5]:
wine_reviews.describe()

          Unnamed: 0         points          price
count  129971.000000  129971.000000  120975.000000
mean    64985.000000      88.447138      35.363389
std     37519.540256       3.039730      41.022218
min         0.000000      80.000000       4.000000
25%     32492.500000      86.000000      17.000000
50%     64985.000000      88.000000      25.000000
75%     97477.500000      91.000000      42.000000
max    129970.000000     100.000000    3300.000000

This method generates a high-level summary of the attributes of the given column. It is type-aware, meaning that its output changes based on the data type of the input. The output above only makes sense for numerical data; for string data here's what we get:

In [6]:
wine_reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

If you want to get some particular simple summary statistic about a column in a DataFrame or a Series, there is usually a helpful pandas function that makes it happen.

For example, to see the mean of the points allotted (e.g. how well an averagely rated wine does), we can use the mean() function:

In [7]:
wine_reviews.points.mean()

np.float64(88.44713820775404)

In [8]:
## To see a list of unique values we can use the unique() function:

wine_reviews.taster_name.unique()

<StringArray>
[     'Kerin O’Keefe',         'Roger Voss',       'Paul Gregutt',
 'Alexander Peartree',  'Michael Schachner', 'Anna Lee C. Iijima',
     'Virginie Boone',      'Matt Kettmann',                  nan,
   'Sean P. Sullivan',         'Jim Gordon',     'Joe Czerwinski',
   'Anne Krebiehl MW',      'Lauren Buzzeo',      'Mike DeSimone',
       'Jeff Jenssen',    'Susan Kostrzewa',       'Carrie Dykes',
        'Fiona Adams',  'Christina Pickard']
Length: 20, dtype: str

In [9]:
## To see a list of unique values and how often they occur in the dataset, we can use the value_counts() method:

wine_reviews.taster_name.value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

### Maps

A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!

There are two mapping methods that you will use often.

map() is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:

In [10]:
wine_reviews_points_mean = wine_reviews.points.mean()
wine_reviews.points.map(lambda p : p - wine_reviews_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

The function you pass to map() should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

In [11]:
def remean_points(row):
    row.points = row.points - wine_reviews_points_mean
    return row

wine_reviews.apply(remean_points, axis = 'columns')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

If we had called reviews.apply() with axis='index', then instead of passing a function to transform each row, we would need to give a function to transform each column.

Note that map() and apply() return new, transformed Series and DataFrames, respectively. They don't modify the original data they're called on. If we look at the first row of reviews, we can see that it still has its original points value.

In [12]:
wine_reviews.head(1)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

Pandas provides many common mapping operations as built-ins. For example, here's a faster way of remeaning our points column:

In [13]:
wine_reviews_points_mean = wine_reviews.points.mean()
wine_reviews.points - wine_reviews_points_mean

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In this code we are performing an operation between a lot of values on the left-hand side (everything in the Series) and a single value on the right-hand side (the mean value). Pandas looks at this expression and figures out that we must mean to subtract that mean value from every value in the dataset.

Pandas will also understand what to do if we perform these operations between Series of equal length. For example, an easy way of combining country and region information in the dataset would be to do the following:

In [14]:
wine_reviews.country + " - " + wine_reviews.region_1

0                     Italy - Etna
1                              NaN
2           US - Willamette Valley
3         US - Lake Michigan Shore
4           US - Willamette Valley
                    ...
129966                         NaN
129967                 US - Oregon
129968             France - Alsace
129969             France - Alsace
129970             France - Alsace
Length: 129971, dtype: str

These operators are faster than map() or apply() because they use speed ups built into pandas. All of the standard Python operators (>, <, ==, and so on) work in this manner.

However, they are not as flexible as map() or apply(), which can do more advanced things, like applying conditional logic, which cannot be done with addition and subtraction alone.

In [15]:
## 1. What is the median of the points column in the wine_reviews

wine_reviews.points.median()

np.float64(88.0)

In [16]:
median_points = wine_reviews.points.median()
wine_reviews.points.map(lambda p : p - median_points)

0        -1.0
1        -1.0
2        -1.0
3        -1.0
4        -1.0
         ...
129966    2.0
129967    2.0
129968    2.0
129969    2.0
129970    2.0
Name: points, Length: 129971, dtype: float64

In [17]:
## What countries are represented in the dataset? (Your answer should not include any duplicates.)

countires = wine_reviews.country.unique()
countires

<StringArray>
[                 'Italy',               'Portugal',                     'US',
                  'Spain',                 'France',                'Germany',
              'Argentina',                  'Chile',              'Australia',
                'Austria',           'South Africa',            'New Zealand',
                 'Israel',                'Hungary',                 'Greece',
                'Romania',                 'Mexico',                 'Canada',
                      nan,                 'Turkey',         'Czech Republic',
               'Slovenia',             'Luxembourg',                'Croatia',
                'Georgia',                'Uruguay',                'England',
                'Lebanon',                 'Serbia',                 'Brazil',
                'Moldova',                'Morocco',                   'Peru',
                  'India',               'Bulgaria',                 'Cyprus',
                'Armenia',            'Switzerland', 'Bosnia and Herzegovina',
                'Ukraine',               'Slovakia',              'Macedonia',
                  'China',                  'Egypt']
Length: 44, dtype: str

In [18]:
wine_reviews.country.unique()

<StringArray>
[                 'Italy',               'Portugal',                     'US',
                  'Spain',                 'France',                'Germany',
              'Argentina',                  'Chile',              'Australia',
                'Austria',           'South Africa',            'New Zealand',
                 'Israel',                'Hungary',                 'Greece',
                'Romania',                 'Mexico',                 'Canada',
                      nan,                 'Turkey',         'Czech Republic',
               'Slovenia',             'Luxembourg',                'Croatia',
                'Georgia',                'Uruguay',                'England',
                'Lebanon',                 'Serbia',                 'Brazil',
                'Moldova',                'Morocco',                   'Peru',
                  'India',               'Bulgaria',                 'Cyprus',
                'Armenia',            'Switzerland', 'Bosnia and Herzegovina',
                'Ukraine',               'Slovakia',              'Macedonia',
                  'China',                  'Egypt']
Length: 44, dtype: str

In [19]:
## 3. How often does each country appear in the dataset? Create a Series reviews_per_country mapping countries to the count of reviews of wines from that country.

reviews_per_counrty = wine_reviews.country.value_counts()
reviews_per_counrty

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Czech Republic               12
Serbia                       12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [20]:
wine_reviews.country.value_counts()

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Czech Republic               12
Serbia                       12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

In [21]:
## 4. Create variable centered_price containing a version of the price column with the mean price subtracted.

## (Note: this 'centering' transformation is a common preprocessing step before applying various machine learning algorithms.)

cetntered_price = wine_reviews.price.mean()
wine_reviews.price.map(lambda p : p - cetntered_price)       ## incoreect one

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [22]:
cetntered_price = wine_reviews.price - wine_reviews.price.mean()
cetntered_price

0               NaN
1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

In [23]:
## I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.

bargain_wine = wine_reviews.title.loc[(wine_reviews.points / wine_reviews.price).idxmax()]
bargain_wine

'Bandit NV Merlot (California)'

In [24]:
## 6. There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset. (For simplicity, let's ignore the capitalized versions of these words.)

descriptor_counts = descriptor_counts = pd.Series([
    wine_reviews.description.str.contains("tropical").sum(),
    wine_reviews.description.str.contains("fruity").sum()
], index=["tropical", "fruity"])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [25]:
## We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

## Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

## Create a series star_ratings with the number of stars corresponding to each review in the dataset.

star_ratings = wine_reviews.points.apply(lambda p :3 if p >= 95 else (2 if p >= 85 else 1))
star_ratings[wine_reviews.country == "Canada"] = 3
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Name: points, Length: 129971, dtype: int64

### lambda function :

In [26]:
## normal syntex of lambda function in pything
def func(p):
    return p

In [27]:
## same thing but in shorter and can be used in pandas :
lambda p : p

lambda p: ...

p = each value from your column (one by one)

... = what you want to do with that valu

In [28]:
## Example : lambda p : p:

wine_reviews.price.map(lambda p : p)    ## take each price ---> return it as it is

0          NaN
1         15.0
2         14.0
3         13.0
4         65.0
          ...
129966    28.0
129967    75.0
129968    30.0
129969    32.0
129970    21.0
Name: price, Length: 129971, dtype: float64

In [29]:
## Example : lambda p : p * 2 

wine_reviews.price.map(lambda p : p * 2)    ## Take each price ---> myltiply by 2

0           NaN
1          30.0
2          28.0
3          26.0
4         130.0
          ...
129966     56.0
129967    150.0
129968     60.0
129969     64.0
129970     42.0
Name: price, Length: 129971, dtype: float64

In [30]:
## Example : lambda p : 3

wine_reviews.points.map(lambda p : 3)   ## Take each value ---> ignore it ---> always return 3

0         3
1         3
2         3
3         3
4         3
         ..
129966    3
129967    3
129968    3
129969    3
129970    3
Name: points, Length: 129971, dtype: int64

In [31]:
wine_reviews.points.map(lambda p : 3 if p >= 95 else 2 if p >= 85 else 1 )

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Name: points, Length: 129971, dtype: int64